import {Plot3D} from '../scatterPlot3D.js'
import {Vanodi} from '../resources/vanodi.js'
import {SelectPoints} from '../js/selections.js'

// Script for interface with NGCHM
export var VAN = new Vanodi({
	op: 'register',
	name: 'ScatterPlot3D',
	axes: [
		{
			axisLabel: 'Points Axis',
			coco: [
				{
					name: 'Coordinate', 
					baseid: 'coordinate',
					min: 3, 
					max: 3,
					helpText: 'Coordinates in Scatter Plot 3D'
				},
				{
					name: 'Color By',
					baseid: 'covariate',
					min: 1,
					max: 1,
					helpText: 'Covariate used to color points in Scatter Plot 3D'
				}
			],
		}
	],
	options: [
		{ label: 'Show Origin Axes', type: 'dropdown', choices: [
			{label: 'Yes', value: 'yes'},
			{label: 'No', value: 'no'}
		], helpText: 'Display XYZ axes at origin'},
		{ label: 'Color Axes', type: 'dropdown', choices: [
			{label: 'On', value: 'on'},
			{label: 'Off', value: 'off'}
		], helpText: 'Color each of the X, Y, and Z axes a different color'},
		{ label: 'Background Color', type: 'dropdown', choices: [
			{label: 'White', value: 'white'},
			{label: 'Ivory', value: 'ivory'},
			{label: 'Black', value: 'black'},
			{label: 'Grey', value: 'grey'}
		]},
		{ label: 'Highlight Color', type: 'dropdown', choices: [
			{label: 'Black', value: 'black'},
			{label: 'White', value: 'white'},
			{label: 'Grey', value: 'grey'},
			{label: 'Blue', value: 'blue'}, 
			{label: 'Pink', value: 'hotpink'}
		], helpText: 'Color for highlighting points under cursor or selected from NGCHM'},
		{ label: 'Legend Hover Transparency', type: 'dropdown', choices: [
			{label: 'Medium', value: 0.2},
			{label: 'Complete', value: 0.0},
			{label: 'Faint', value: 0.1},
			{label: 'Dark', value: 0.5},
			{label: 'None', value: 1.0}
		], helpText: 'For hovering over legend: transparency of non-hovered groups.'},
		{ label: 'Point Size', type: 'dropdown', choices: [
			{label: 'Medium', value: 0.1},
			{label: 'Small', value: 0.04},
			{label: 'Large', value: 0.2}
		]}
	]
})

VAN.addMessageListener('plot', function(vanodi) {
	let plotOptions = {
		xLabel: vanodi.config.axes[0].coordinates[0].label, 
		yLabel: vanodi.config.axes[0].coordinates[1].label, 
		zLabel: vanodi.config.axes[0].coordinates[2].label, 
		backgroundColor: vanodi.config.options['Background Color'],
		highlightColor: vanodi.config.options['Highlight Color'],
		hoverOpacity: vanodi.config.options['Legend Hover Transparency'],
		pointSize: vanodi.config.options['Point Size'],
		showOriginAxes: vanodi.config.options['Show Origin Axes'],
		colorAxes: vanodi.config.options['Color Axes'],
		legendTitle: vanodi.config.axes[0].covariates[0].label
	}
	// organize data to plot
	let plotData = []
	vanodi.data.axes[0].covariateColors[0].forEach( (covColor,idx) => {
		plotData.push({
			x: vanodi.data.axes[0].coordinates[0][idx],
			y: vanodi.data.axes[0].coordinates[1][idx],
			z: vanodi.data.axes[0].coordinates[2][idx],
			batch: vanodi.data.axes[0].covariates[0][idx],
			color: covColor,
			id: vanodi.data.axes[0].actualLabels[idx]
		})
	})
	Plot3D.ngchmAxis = vanodi.config.axes[0].axisName;
	if (vanodi.data.axes[0].hasOwnProperty('selectedLabels')) {
		Plot3D.selectedPointIds = vanodi.data.axes[0].selectedLabels
	} else {
		Plot3D.selectedPointIds = []
	}
	Plot3D.nonce = vanodi.nonce
	Plot3D.createPlot(plotData,plotOptions)
})

/* Message listener to highlight points on the scatter plot that were selected 
   on the NGCHM
*/
VAN.addMessageListener ('makeHiLite', function hiliteMessageHandler (vanodi) {
	if (Plot3D.ngchmAxis && Plot3D.ngchmAxis.toLowerCase() != vanodi.data.axis.toLowerCase()) {
		return false;
	}
	SelectPoints.clearSelectedPointIds();
	SelectPoints.selectPoints(vanodi.data.pointIds)
});

/* Message listener for request from NGCHM to send data from plugin.

   This listener is for a request from the NGCHM to send data generated by ScatterPlot3D,
   and required for recreating a given view of the scatter plot. This data did not come originally
   from the NGCHM.
*/
VAN.addMessageListener('requestForPluginData', function requestDataHandler(vanodi) {
	VAN.postMessage({
		op: 'sendingPluginData',
		pluginData: {spherical: Plot3D.spherical}
	})
})

/* Message listener for sent plugin-only data from NGCHM

   This listener is for receiving data from the NGCHM that is required for recreating a 'saved state'.
*/
VAN.addMessageListener('savedPluginData', function addSavedData(vanodi) {
	if (vanodi.dataFromPlugin != undefined) {
		sessionStorage.setItem(Plot3D.nonce, JSON.stringify(vanodi.dataFromPlugin.spherical));
		Plot3D.setSphericalCoordinates(vanodi.dataFromPlugin.spherical);
		Plot3D.saveSphericalCoordinates();
	}
})

